permalink: /posts/:title
markdown: kramdown
highlighter: rogue
kramdown:
  #input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap

name: Max Meldrum
url: "http://Max-Meldrum.github.io"
baseurl: ""
profile: profile.jpeg
description: Home to Max Meldrum
twitter:  meldruum
github: https://github.com/Max-Meldrum
